module.exports.TABS = {
  BRUINCAST: 0,
  VIDEO_RESERVES: 1,
  DIGITAL_AUDIO_RESERVES: 2,
  MEDIA_GALLERY: 3,
  ADMIN_PANEL: 4,
};

module.exports.ADMIN_PANEL_TABS = {
  SETTINGS: 0,
  LISTINGS_BRUINCAST: 1,
  LISTINGS_VIDEORESERVES: 2,
};

module.exports.MEDIA_TYPE = {
  BRUINCAST: 'bruincast',
  VIDEO_RESERVES: 'videores',
};
