name: 'Commit Message Check'
on: push

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(^Bump[a-zA-Z0-9 ./@_-]+)|(CANVAS-[0-9]+\ -\ .{5,})'
          error: 'Commit message needs to match CANVAS-<TICKET NUMBER> - <Description>, where Description is at least 5 characters. Dependabot messages that start with "Bump" are ignored.'
