# From: https://github.com/hallee/eslint-action/issues/23#issuecomment-674761123
name: Lint

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # ~~~ CACHING ~~~
        # The following is just to do caching of yarn and eslint, it's not necessary to get linting to work
        # I would recommend first trying without

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache action
        uses: actions/cache@v2.1.5
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./.eslintcache
          key: ${{ runner.os }}-yarn-lint-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-lint-

       # ~~~ END CACHING ~~~

      - name: Setup Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint