# Performs automated tests on pushes.

name: Automated testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Copy .env file
        uses: canastro/copy-file-action@master
        with:
          source: '.env.dist'
          target: '.env'
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-replica-set: rs0
      - name: Run tests
        run: yarn test
